
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Information About Yourself
your_name                                 : Julien Pelegri
your_link                                 :
your_city                                 : Paris
email_address                             :
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :


app_icon                                  : # assets/appicon.png


plugins:
  - jekyll-feed
  - jekyll-sitemap

# Sass settings
sass:
  style: :compressed

# Build settings
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - README.md
  - CNAME
  - assets/sass
  - LICENSE


# Markdown rendering
markdown: kramdown
